### PR TITLE
Split into shared project with PCL implementation

### PR DESCRIPTION
**Pull request by joshcomley**
Hi there,

Today I forked your code and created a version that contains both a .NET 3.5 implementation and a Portable Class Library (PCL). There is no code duplication because I have used Shared Projects (it should be fine to open in Visual Studio 2013). I have also signed the projects with your pfx file that was already there.

I have had to make some small changes to make it compatible with the PCL libraries, but nothing that has affected the tests.

- DataContract is now used in place of XmlSerializer
- In PCLs you have to use myType.GetTypeInfo() to access a lot of type information, but if you look at TypeExtensions.cs in the shared project you can see how I solved this in a nice clean, simple manner without having to have lots of conditions throughout your code
- I think that was it...

You can take out the code signing easily enough, but this update enables people write their argument logic in their shared PCLs and use your lovely fluent syntax - and then pass that back to the command line apps.

All the best,
Josh

### CODE REVIEW

**Comment by siywilliams** [comment]
yc1b4wa

Thanks Josh, will get round to looking at this shortly.

**Comment by joshcomley** [comment]
Haha, enjoy! And thanks for the cool project :)

**Comment by siywilliams** [comment]
I'm having trouble loading the two new shared projects (shproj), have you done this in VS2015?

**Comment by joshcomley** [comment]
Yes I have. I'll take a look later when I'm back home to open in VS2013 and
make sure it loads. Do you have the latest updates for VS2013? I'll make
sure it works later and commit any changes. Sorry, I would have checked
before but I don't have VS2013 on my main development laptop :)

**Comment by siywilliams** [comment]
I have 2013 Update 4 but I was missing an extension, which then confused me as it was trying to force me to have a WP developers license but I managed to knock it on the head.

Long story short I've got it compiling locally, although I think this is going to be a challenge to get TeamCity setup correctly to build it appropriately. Just having a look at the new structure and how these Shared projects work - not something I've come across before.

**Comment by siywilliams** [comment]
I've got a bit more work to do to get the build system working with these changes but I'll merge it now

**Pull request merged**
